global:
  replicaCount: 1
  name: fleetman
  repository: supinfo4kube
  env: 
    - name: SPRING_PROFILES_ACTIVE
      value: production-microservice
  image:
    tag: "1.0.1"
  volume:
    storage: 4Gi
    accessMode: ReadWriteOnce

deployments:
  queue:
    image:
      repository: /queue
    environment: disable

  position-simulator:
    image:
      repository: /position-simulator

  position-tracker:
    image:
      repository: /position-tracker

  api-gateway:
    image:
      repository: /api-gateway

  webapp:
    image:
      repository: /web-app
      tag: 1.0.0

  mongodb:
    image:
      repository: mongo
      tag: 3.6.23
    volume:
      mountPath: /data/db
    environment: disable

services:
  queue:
    type: NodePort
    ports:
      - id: 1
        port: 8161
        nodePort: 30010
      - id: 2
        port: 61616

  position-tracker:
    type: ClusterIP
    ports:
      - port: 8080

  api-gateway:
    type: ClusterIP
    ports:
      - port: 8080

  webapp:
    type: NodePort
    ports:
      - port: 80
        nodePort: 30080

  mongodb:
    type: ClusterIP
    ports:
      - port: 27017

volumes:
  mongodb-pv-claim:
    accessModes:
    resources:
      requests:
        storage: