{{- range $key, $value := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: {{ $value.replicas | default $.Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          {{- if hasPrefix "/" $value.image.repository }}
          image: "{{ $.Values.global.repository }}{{ $value.image.repository }}:{{ $value.image.tag | default "latest" }}"
          {{- else }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag | default "latest" }}"
          {{- end}}
          imagePullPolicy: "IfNotPresent"
          {{- if eq $value.environment "enable"}}
          env:
            {{- range $envkey, $envvalue := $.Values.global.env }}
            - name: {{ $envvalue.name }}
              value: {{ $envvalue.value }}
            {{- end}}
          {{- end }}
      {{- if $value.volume}}
          volumeMounts:
            - mouthPath: {{ $value.volume.mountPath }}
              name: {{ $key }}
      volumes:
        - name: {{ $key }}
          persistentVolumeClaim: 
            claimName: mongo-data
      {{- end }}
{{- end }}