{{- range $key, $value := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: {{ $value.replicas | default $.Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          {{- if hasPrefix "/" $value.image.repository }}
          image: "{{ $.Values.global.repository }}{{ $value.image.repository }}:{{ $value.image.tag | default $.Values.global.image.tag }}"
          {{- else }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag | default $.Values.global.image.tag }}"
          {{- end}}
          imagePullPolicy: "IfNotPresent"
          {{- if not (eq $value.environment "disable") }}
          envFrom:
            - secretRef:
                name: env-secret
          {{- end }}
          resources:
            limits:
              cpu: {{- if index $.Values.global.resources "limits" }}
                {{- if index $.Values.global.resources.limits "cpu" }} {{ $.Values.global.resources.limits.cpu }}{{ end }}
              {{- end }}
              memory: {{- if index $.Values.global.resources "limits" }}
                {{- if index $.Values.global.resources.limits "memory" }} {{ $.Values.global.resources.limits.memory }}{{ end }}
              {{- end }}
            requests:
              cpu: {{- if index $.Values.global.resources "requests" }}
                {{- if index $.Values.global.resources.requests "cpu" }} {{ $.Values.global.resources.requests.cpu }}{{ end }}
              {{- end }}
              memory: {{- if index $.Values.global.resources "requests" }}
                {{- if index $.Values.global.resources.requests "memory" }} {{ $.Values.global.resources.requests.memory }}{{ end }}
              {{- end }}
          {{- if and (hasKey $value "probes") (hasKey $value.probes "startupProbe") $value.probes.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $.Values.global.probes.startupProbe.path }}
              port: {{ $.Values.global.probes.startupProbe.port }}
            initialDelaySeconds: {{ $.Values.global.probes.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.global.probes.startupProbe.periodSeconds }}
          {{- end }}

      {{- if $value.volume}}
          volumeMounts:
            - mountPath: {{ $value.volume.mountPath }}
              name: {{ $key }}-0
      volumes:
        - name: {{ $key }}-0
          persistentVolumeClaim: 
            claimName: mongodb-pv-claim
      {{- end }}
{{- end }}