{{- range $key, $value := .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}
spec:
  accessModes: 
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
{{- end }}