{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.global.name }}-{{ $key }}
  labels:
    app: {{ $key }}
spec:
  {{- if $value.type }}
  type: {{ $value.type }}
  {{- end}}
  {{- if $value.clusterIp }}
  clusterIP: {{ $value.clusterIp }}
  {{- end}}
  {{- with $value.ports }}
  ports:
    {{- range $portKey, $portValue := $value.ports }}
    {{- if $portValue.id}}
    - name: {{ $key -}}-{{ $portValue.id -}}-service
    {{- else }}
    - name: {{ $key -}}-service
    {{- end }}
      {{- if $portValue.protocol}}
      protocol: {{ $portValue.protocol }}
      {{- end }}
      port: {{ $portValue.port }}
      {{- if $portValue.nodePort}}
      nodePort: {{ $portValue.nodePort }}
      {{- end }}
      {{- if $portValue.targetPort}}
      targetPort: {{ $portValue.targetPort }}
      {{- end }}
    {{- end}}
  {{- end}}
  selector:
    app: {{ $key }}
{{- end }}