{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $key }}
  name: {{ $key }}
spec:
  {{- if $value.type }}
  type: {{ $value.type }}
  {{- end}}
  {{- if $value.clusterIp }}
  clusterIP: {{ $value.clusterIp }}
  {{- end}}
  {{- with $value.ports }}
  ports:
    {{- range $portKey, $portValue := $value.ports }}
    {{- if $portValue.id}}
    - name: {{ $key -}}{{ $portValue.id -}}-service
    {{- else }}
    - name: {{ $key -}}-service
    {{- end }}
      port: {{ $portValue.port }}
      {{- if $portValue.targetPort}}
      targetPort: {{ $portValue.targetPort }}
      {{- else if $portValue.port}}
      targetPort: {{ $portValue.port }}
      {{- end }}
    {{- end}}
  {{- end}}
  selector:
    app: {{ $key }}
{{- end }}